### ISSUE TITLE
Lag Spikes when using "/finditem"

### ISSUE THREAD

**Issue by ClxdyWindows** [myzticbean/QSFindItemAddOn#12]
When using "/finditem" there is a lag spike for a while. I DM'ed you a spark profiler

**Comment by myzticbean** [comment]
Working on it, thanks for bringing to my notice.

**Comment by myzticbean** [comment]
@ClxdyWindows Please update to 2.0.5.6 from [here](https://modrinth.com/plugin/shop-search/version/2.0.5.6-RELEASE).
