### ISSUE TITLE
[Bug] Item Stock says unknown

### ISSUE THREAD

**Issue by Kyrobi** [myzticbean/QSFindItemAddOn#17]
I'm using:
QuickShop-Hikari (6.0.0.10)
QSFindItemAddOn (2.0.5.6-RELEASE)

When I use the /finditem command, all the shops show up as unknown for their stock:
![image](https://github.com/myzticbean/QSFindItemAddOn/assets/20980266/88d83931-742f-4825-a4f8-9d37d9bdf1d4)

However, when you go to the shop, the shop does indeed have items in the shop:
![image](https://github.com/myzticbean/QSFindItemAddOn/assets/20980266/eeca2bf2-2e8e-4fe4-8242-208d087a39e0)

**Comment by myzticbean** [comment]
@Kyrobi As per QS Hikari v6.0+, all stock/space values are now fetched from the Hikari database and doesn't load the chunk anymore to reduce lag. So, an unknown value means the stock/space value has not been cached yet in database by Hikari. I'll see what I can do.

**Comment by myzticbean** [comment]
@Kyrobi I have tried to fix this issue, but can you do me a favor and try it out on your server if it fixes the issue? You can find the link to download from below.
https://modrinth.com/plugin/shop-search/version/2.0.5.7-SNAPSHOT
Thanks!

**Comment by Kyrobi** [comment]
Sure! I'll try it out tomorrow. In the meantime, I wrote something to loop through all the chests and manually updated them. I'll clear my cache and try tomorrow.

**Comment by Kyrobi** [comment]
It seems like the plugin is correctly able to load the stocks. However, it spams the console with the debug message as follows (I'm not sure if it's still manually calling Shop#getRemainingStock() once all the items are in the cache)

![image](https://github.com/myzticbean/QSFindItemAddOn/assets/20980266/c3048cad-602f-4a1e-a045-c5cdd8650bfe)

And then for unlimited shops, it shows up as -1:

![javaw_JHOEKMwp6Y](https://github.com/myzticbean/QSFindItemAddOn/assets/20980266/5203f1d5-5e35-49e1-b3d6-d2aebd4962cc)

**Comment by myzticbean** [comment]
@Kyrobi does running the same exact command again still spam the console? Ideally once it has fetched stock value from store, the next time it should fetch it from cache. I'll remove that debug msg in release build and also look into that -1 for unlimited.

**Comment by Kyrobi** [comment]
Every time I open the the /finditem menu again, it prints the message to the console

**Comment by myzticbean** [comment]
Fixed in 2.0.5.7 release. Reopen if issue persist.
