### ISSUE TITLE
Olzie's PlayerWarps Suggestion

### ISSUE THREAD

**Issue by lukemango** [myzticbean/QSFindItemAddOn#38]
Please add an option to only list the warp that's nearest to the shop that the player owns, we're having issues with multiple warps in close proximity teleporting the player to the wrong warp as it's not the same warp as the player owns. This option would fix that.

Thank you.

**Comment by myzticbean** [comment]
Thanks for contributing @lukemango ! You can download the plugin from [here](https://github.com/myzticbean/QSFindItemAddOn/releases/tag/v2.0.6.2-release). Closing this issue.
