### ISSUE TITLE
Custom command on click

### ISSUE THREAD

**Issue by Pandemonious** [myzticbean/QSFindItemAddOn#49]
Hello again,

Is it possible to configure a custom command to execute when you click on a shop instead of teleportation?

For example, when clicking, I'd like to use Oth3r's DirectionHud to have it set a waypoint to the shop's destination. So the command would use the coordinates placeholder from the item lore and would be something like directionhud dest set {SHOP_LOC}

This may require having separate placeholders for X Y and Z of the {SHOP_LOC} placeholder. (As a matter of fact, directionhud doesn't accept commas in the syntax, so I believe it would have to be three separate placeholders)

Just a suggestion, not an issue! Thank you for reading! I look forward to seeing what you may come up with

**Comment by myzticbean** [comment]
@Pandemonious Try out this version:
https://modrinth.com/plugin/shop-search/version/2.0.7.0-SNAPSHOT

**Comment by myzticbean** [comment]
Added in 2.0.7.0. Closing issue.
