### ISSUE TITLE
Revealshop + Hideshop do not work

### ISSUE THREAD

**Issue by ClxdyWindows** [myzticbean/QSFindItemAddOn#5]
Fairly simple, these commands just don't function. They give us the "The block you are looking at is not a shop!" message even when looking at a shop.

**Comment by myzticbean** [comment]
@ClxdyWindows 
Just to confirm, you are looking at the chest block and not the sign right? 
Is it a double chest?
Which quickshop, hikari or reremake?

**Comment by ClxdyWindows** [comment]
@myzticbean It is Hikari quickshop. It doesn't function with a double chest, or a normal chest. I have tried looking at both the sign and the chest, however neither work. 

We are running:

QuickShop-Hikari 5.2.0.6
PurPur Build #2094

**Comment by myzticbean** [comment]
@myzticbean can you DM me on discord @myzticbean? To get a better understanding of this issue, would like to try it out on your server.

**Comment by myzticbean** [comment]
Fixed as of 2.0.5.6 version. If issue persists, please reopen.
