### ISSUE TITLE
QS Search Item doesn't work in newest version

### ISSUE THREAD

**Issue by ClxdyWindows** [myzticbean/QSFindItemAddOn#9]
Updated to 5.0.5.4, when you use "/finditem TO_BUY / TO_SELL" it says that an internal error occurred. 

https://paste.helpch.at/ubojucaqur.rb

**Comment by myzticbean** [comment]
Hey @ClxdyWindows! This bug should be fixed in 2.0.5.5 build. Download from [here](https://modrinth.com/plugin/shop-search/version/2.0.5.5-RELEASE).
